version: "3"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/symfony
    expose:
      - "9001"
    ports:
      - 8000:8000
    networks:
      - symfony

networks:
  symfony:
